# Generated by Django 5.0.2 on 2024-03-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentSubjectHandle', '0003_contentsubject_idsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('idQuestion', models.AutoField(primary_key=True, serialize=False)),
                ('contentQuestion', models.TextField()),
                ('levelOfDifficult', models.CharField(max_length=200)),
                ('answerA', models.TextField()),
                ('answerB', models.TextField()),
                ('answerC', models.TextField()),
                ('answerD', models.TextField()),
                ('correctAnswer', models.CharField(max_length=10)),
                ('idContentSubject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contentSubjectHandle.contentsubject')),
            ],
        ),
    ]
