# Generated by Django 5.0.2 on 2024-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
