# Generated by Django 5.0.2 on 2024-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=255)),
                ('describe_course', models.CharField(max_length=255)),
            ],
        ),
    ]
