# Generated by Django 5.0.2 on 2024-03-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='describe_course',
            new_name='describeCourse',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id_course',
            new_name='idCourse',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name_course',
            new_name='nameCourse',
        ),
    ]
