# Generated by Django 5.0.2 on 2024-04-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_account_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('idTransactionHistory', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('time', models.DateField(default='00/00/2000')),
                ('idAccount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
            ],
        ),
    ]
