# Generated by Django 5.0.2 on 2024-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_statistic_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='position',
            field=models.CharField(default='Student', max_length=255),
        ),
    ]
