# Generated by Django 5.0.2 on 2024-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject', models.CharField(max_length=255)),
                ('describe_subject', models.CharField(max_length=255)),
            ],
        ),
    ]
