# Generated by Django 5.0.2 on 2024-03-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0004_rename_namecourse_subject_idcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleContent',
            fields=[
                ('idTitleContent', models.AutoField(primary_key=True, serialize=False)),
                ('titleContent', models.CharField(max_length=255)),
                ('idSubject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subject')),
            ],
        ),
    ]
