# Generated by Django 5.0.2 on 2024-03-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentSubjectHandle', '0002_contentsubject'),
        ('subject', '0004_rename_namecourse_subject_idcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubject',
            name='idSubject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='subject.subject'),
            preserve_default=False,
        ),
    ]
