# Generated by Django 5.0.2 on 2024-03-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idAccount', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaction_history', models.IntegerField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('accountName', models.CharField(max_length=255)),
                ('emailAddress', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('infringe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('activationCode', models.CharField(max_length=255)),
                ('point', models.IntegerField(max_length=255)),
                ('learningOutcomes', models.IntegerField(max_length=255)),
            ],
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('degree', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('bankAccountNumber', models.CharField(max_length=255)),
                ('wage', models.CharField(max_length=255)),
            ],
            bases=('account.account',),
        ),
    ]
