# Generated by Django 5.0.2 on 2024-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_transaction_history',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='learningOutcomes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='point',
            field=models.IntegerField(),
        ),
    ]
