# Generated by Django 5.0.2 on 2024-04-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiry',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='id_transaction_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='infringe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='activationCode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='learningOutcomes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
