# Generated by Django 5.0.2 on 2024-04-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=models.DateTimeField(default='11/11/2000'),
        ),
    ]
