# Generated by Django 5.0.2 on 2024-04-19 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2000, 11, 11, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id_transaction_history',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='infringe',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='activationCode',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
