# Generated by Django 5.0.2 on 2024-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
