# Generated by Django 5.0.2 on 2024-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_accountname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(default='Student', max_length=255),
        ),
    ]
